services:
  mongodb:
    container_name: tinder-ai-mongodb  # Unique container name
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=mydatabase'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017:27017'  # Fixed mapping: host_port:container_port
    volumes:
      - ./db/volume_mongo:/data/db
#    healthcheck:
#      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "--silent" ]
#      retries: 10
#      interval: 3s
#      timeout: 30s
    networks:
      - tinder-network

  ollama:
    container_name: tinder-ai-ollama
    image: 'ollama/ollama:latest'
    ports:
      - '11434:11434'
    volumes:
      - ./pull-llama3.sh:/ollama-app/pull-llama3.sh # Mount the script from the host
    working_dir: /ollama-app  # Set working directory
    networks:
      - tinder-network

networks:
  tinder-network:
    name: tinder-network
