
server:
  port: 9990

spring:
  application:
    name: tinder-ai-backend

  # devtools
  devtools:
    add-properties: true

  # AI Model configuration
  ai:
    # OPEN_AI
    openai:
      api-key: ${SPRING_AI_OPENAI_API_KEY}
      chat:
        enabled: true
        options:
          model: gpt-4o-mini
          temperature: 0.7

    # OLLAMA
    ollama:
      base-url: http://localhost:11434
      chat:
        enabled: true
  data:
    mongodb:
#      port: 63804
      uri: mongodb://root:secret@localhost:63804/mydatabase?authSource=admin

logging:
  level:
    com.learning.tinderaibackend: debug
