
server:
  port: 9990

spring:
  application:
    name: tinder-ai-backend

  # devtools
  devtools:
    add-properties: true

  # AI Model configuration
  ai:
    # OPEN_AI
    openai:
      api-key: ${SPRING_AI_OPENAI_API_KEY}
      chat:
        enabled: true
        options:
          model: gpt-4o-mini
          temperature: 0.7

    # OLLAMA
    ollama:
      base-url: http://localhost:11434
      chat:
        enabled: true
        model: llama3.1
        options:
          temperature: 0.8

  # Datasource : mongo
  data:
    mongodb:
#      port: 63804
      uri: mongodb://root:secret@localhost:63804/mydatabase?authSource=admin

logging:
  level:
    com.learning.tinderaibackend: debug

tinderai:
  character:
    user: "{'profileId':'8b0e4a15-95c2-45bd-937d-f111a8bfbfec', 'firstName':'Vivek', 'lastName':'Kumar', 'age':27, 'ethnicity':'Indian', 'gender':'MALE', 'bio':'Software engineer, teacher and learner. I like reading and making things.', 'imageUrl':'', 'myersBriggsPersonalityType':'INTP'}"
#    user:
#      id: "user"
#      firstName: "Vivek"
#      lastName: "Kumar"
#      age: 27
#      ethnicity: "Indian"
#      gender: "MALE"
#      bio: "Software engineer, teacher and learner. I like reading and making things."
#      imageUrl: ""
#      myersBriggsPersonalityType: "INTP"

startup-actions:
  initializeProfiles: false

profiles:
  file-path: newProfiles.json
